name: Craete Inputs Summary
description: |
  This action creates a summary of the inputs provided to the workflow.

inputs:
  workflow-inputs:
    description: "The inputs provided to the workflow. This should be a JSON string."
    required: true

runs:
  using: composite
  steps:
    - name: Create Inputs Summary
      uses: actions/github-script@v7
      with:
        script: |
          const inputs = JSON.parse(process.env.INPUTS);

          const parametersTable = [
            [{ data: 'key', header: true}, { data: 'value', header: true }],
            ['branch', '${{ github.ref_name }}']
          ];
          console.log(parametersTable)

          for ([key, value] of Object.entries(inputs)) {
            parametersTable.push([key, value])
          }

          await core.summary
            .addRaw("### 📝 Inputs \n")
            .addTable(parametersTable)
            .write()
      env:
        INPUTS: ${{ inputs.workflow-inputs }}
