name: Craete Inputs Summary
description: |
  This action creates a summary of the inputs provided to the workflow.

inputs:
  inputs:
    description: "The inputs provided to the workflow."
    required: true

runs:
  using: composite
  steps:
    - run: |
        echo "Hello, ${TARGET}!"
        echo "${fromJSON(inputs.inputs)}"
      shell: bash
      env:
        TARGET: ${{ inputs.inputs }}
