name: Craete Inputs Summary
description: |
  This action creates a summary of the inputs provided to the workflow.

inputs:
  workflow-inputs:
    description: "The inputs provided to the workflow."
    required: true

runs:
  using: composite
  steps:
    # - name: Checkout code
    #   uses: actions/checkout@v4
    #   with:
    #     ref: ${{ github.head_ref }}

    - run: |
        echo $TARGET
      shell: bash
      env:
        TARGET: ${{ inputs.workflow-inputs }}

    - name: Create Inputs Summary
      uses: actions/github-script@v7
      with:
        script: |
          const { INPUTS: inputs } = process.env;
          console.log(inputs);
          console.log(typeof inputs);

          const parametersTable = [
            [{ data: 'key', header: true}, { data: 'value', header: true }],
            ['branch', '${{ github.ref_name }}']
          ];
          console.log(parametersTable)

          for ([key, value] of Object.entries(inputs)) {
              parametersTable.push([key, value])
            }

            await core.summary
              .addRaw("### 📝 Inputs \n")
              .addTable(parametersTable)
              .write()
      env:
        INPUTS: ${{ fromJSON(inputs.workflow-inputs) }}
