name: Craete Inputs Summary
description: |
  This action creates a summary of the inputs provided to the workflow.

inputs:
  workflow-inputs:
    description: "The inputs provided to the workflow."
    required: true

runs:
  using: composite
  steps:
    # - name: Checkout code
    #   uses: actions/checkout@v4
    #   with:
    #     ref: ${{ github.head_ref }}

    - run: |
        echo $TARGET
      shell: bash
      env:
        TARGET: ${{ toJSON(inputs.workflow-inputs }}
