name: Generate reusable workflow docs
run-name: "${{ github.workflow }} for ${{ github.ref_name }} Triggered by: ${{ github.event_name }} [${{ github.sha }}]"

on:
  pull_request:
    paths:
      - ".github/workflows/*.yml"
    paths-ignore:
      - ".github/workflows/*internal*.yml"
permissions:
  contents: write
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    strategy:
      matrix:
        yaml-file:
          [
            .github/workflows/lint.yml,
            .github/workflows/docs-generator.yml,
            .github/workflows/deploy.yml,
            .github/workflows/yaml-lint.yml,
            .github/workflows/github-release.yml,
            .github/workflows/label.yml,
          ]
        include:
          - yaml-file: .github/workflows/lint.yml
            markdown-file: docs/lint.md
          - yaml-file: .github/workflows/docs-generator.yml
            markdown-file: docs/docs-generator.md
          - yaml-file: .github/workflows/deploy.yml
            markdown-file: docs/deploy.md
          - yaml-file: .github/workflows/yaml-lint.yml
            markdown-file: docs/yaml-lint.md
          - yaml-file: .github/workflows/github-release.yml
            markdown-file: docs/github-release.md
          - yaml-file: .github/workflows/label.yml
            markdown-file: docs/label.md
    uses: ./.github/workflows/docs-generator.yml
    with:
      yaml-file: ${{ matrix.yaml-file }}
      markdown-file: ${{ matrix.markdown-file }}
      ref: ${{ github.head_ref }}
