# @see https://zenn.dev/tmknom/books/pragmatic-composite-action/viewer/lint
name: Internal Lint (YAML)
run-name: "${{ github.workflow }} for ${{ github.ref_name }} Triggered by: ${{ github.event_name }} [${{ github.sha }}]"

on:
  pull_request:
    paths: ["**.yml", "**.yaml"]
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call:
    uses: ./.github/workflows/reusable-yaml-lint.yml
    permissions:
      contents: read
