name: Test for reusable-lint
run-name: ${{ github.workflow }} on ${{ github.ref_type }} ${{ github.ref_name }} [${{ github.sha }}]

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/reusable-lint.yml
      - .github/workflows/_internal-test-reusable-lint.yml

concurrency:
  group: test-reusable-lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: test

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: working-directory
        run: |
          echo "working-directory: $PWD"
  test-matrix:
    strategy:
      matrix:
        install-options: ["", "--no-audit --ignore-scripts"]
        include:
          - install-options: ""
            lint-script: "npm run test"
            checkout-ref: ${{ github.ref }}
          - install-options: "--no-audit --ignore-scripts"
            lint-script: "npm run test && npm run test:script"
            checkout-ref: ${{ github.head_ref}}
    uses: ./.github/workflows/reusable-lint.yml
    with:
      install-options: ${{ matrix.install-options }}
      lint-script: ${{ matrix.lint-script }}
      checkout-ref: ${{ matrix.checkout-ref }}
    permissions:
      contents: read
      packages: read

  test-with-token:
    uses: ./.github/workflows/reusable-lint.yml
    with:
      enable-format-check: true
    secrets:
      node-auth-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
