name: Teste for reusable-pre-processing
run-name: "${{ github.workflow }} for ${{ github.ref_name }} Triggered by: ${{ github.event_name }} [${{ github.sha }}]"

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/reusable-pre-processing.yml
      - .github/workflows/_internal-test-reusable-pre-processing.yml

jobs:
  exercise:
    uses: ./.github/workflows/reusable-pre-processing.yml
    with:
      workflow-inputs: ${{ fromJSON({"foo":"bar","hoge":"fuga","boolean":false,"num":123}) }}
