name: Internal Release
run-name: "${{ github.workflow }} for ${{ github.ref_name }} level ${{ inputs.level }} [${{ github.sha }}]"

on:
  workflow_dispatch:
    inputs:
      level:
        type: choice
        required: true
        description: |
          Bump up to [patch / minor / major]
        options:
          - patch
          - minor
          - major
        default: minor

concurrency: ${{ github.workflow }}

jobs:
  call:
    uses: ./.github/workflows/github-release.yml
    with:
      level: ${{ inputs.level }}
    permissions:
      contents: write
