name: Internal Label
run-name: "${{ github.workflow }} for ${{ github.ref_name }} [${{ github.sha }}]"

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call:
    uses: ./.github/workflows/label.yml
    secrets:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
