name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: |
          Required input to set the environment to deploy.
        type: string
        required: true

      working-directory:
        description: |
          Optional. Specifies the directory where the workflow should execute.
          Use this to change the default context if your project has a specific structure.
          Example: "src/app"
        type: string
        required: false
        default: "."

      # Set up Node.js  & install dependencies inputs
      node-version:
        description: |
          Optional. Defines the version of Node.js to use.
          Specify a version number to ensure consistent runtime environments across different executions.
          Example: "20.x"
        type: string
        required: false

      node-version-file:
        description: |
          Optional. Path to a file containing the Node.js version requirement,
          overriding the 'node-version' input if both are specified.
          Default: ".nvmrc"
          Example: "package.json"
        type: string
        required: false
        default: ".nvmrc"

      node-caching:
        description: |
          Optional. Configures caching for Node.js dependencies.
          Leave this as the default or set to an empty string to disable caching.
          Default: "npm"
          Example: "yarn"
        type: string
        required: false
        default: "npm"

      npm-registry-url:
        description: |
          Optional. Sets the npm registry URL, which can be used to define custom registries
          for npm package installations.
          Example: "https://npm.pkg.github.com"
        type: string
        required: false

      npm-scope:
        description: |
          Optional. Specifies the scope for npm package installations,
          affecting where packages are searched for and where they are published.
          Example: "@myorg"
        type: string
        required: false

      checkout-ref:
        description: |
          Optional. Determines the specific reference (such as a branch, tag, or commit SHA) to checkout.
          Example: "refs/heads/feature-branch"
        type: string
        required: false
        # TODO: github.ref?
        default: ${{ github.head_ref }}

      npm-install-options:
        description: |
          Optional. Additional command-line options to pass to the `npm ci` command during dependencies installation.
          Example: "--prefer-offline --no-audit"
        type: string
        required: false

      # Build inputs
      build-command:
        description: |
          Optional input to set the build command to run.
          `npm run build` -> `build`
          `npm run generate` -> `generate` (default)
        type: string
        required: false
        default: "generate"

      build-environments:
        description: |
          Optional input to set the environment variables to use for the build.
          The input syntax corresponds to the setup-environment-variables's one.
        type: string
        required: false
        default: ""

      # Deploy inputs
      s3-sync-command:
        description: |
          Optional input to set the command to deploy the build artifacts to the S3 URI.
          e.g. `./dist s3://example-bucket --delete --exclude "hoge/*"`
        type: string
        required: true

      s3-aws-region:
        description: |
          Optional input to set the AWS region to deploy the build artifacts.
        type: string
        required: false
        default: "ap-northeast-1"

      enable-aws-deploy:
        description: |
          Optional input to set whether to use AWS credentials for the deployment and the command to deploy the build artifacts to the S3 URI.
          `true` -> use AWS credentials and deploy the build artifacts to the S3 URI
          `false` -> print the command to deploy the build artifacts to the S3 URI
        type: boolean
        required: false
        default: true

      # auto merge
      enable-auto-merge:
        description: |
          Whether to perform an automatic merge before deployment.
        type: boolean
        required: false
        default: false

      auto-merge-target-branch:
        description: |
          The target branch to merge into. Used if enable-auto-merge is true.
        type: string
        required: false

      auto-merge-source-ref:
        description: |
          The source ref to merge from. Used if enable-auto-merge is true.
        type: string
        required: false
        default: ${{ github.ref }}

    outputs:
      s3-deploy-command:
        description: |
          The command to deploy the build artifacts to the S3 URI.
        value: ${{ jobs.deploy.outputs.s3-deploy-command }}

    secrets:
      node-auth-token:
        description: |
          Optional secret to set the authentication token to use for the npm commands.
          The input syntax corresponds to the setup-node's one.
          When using GitHub Packages, specify `secrets.GITHUB_TOKEN`
          When using npm, specify `secrets.NPM_AUTH_TOKEN`
        required: false

      github-token:
        description: |
          Optional secret to set the GitHub token to use for the auto merge.
        required: false

      aws-role-arn:
        description: |
          Required secret to set the AWS IAM Role ARN to assume for the deployment.
        required: true

jobs:
  pre-processing:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: create inputs summary
        uses: gawaooooo-sandbox/learn-github-actions-custom/composite/inputs-summary@v3
        with:
          workflow-inputs: ${{ toJSON(inputs) }}

  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    permissions:
      contents: write
      packages: read
      id-token: write
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    outputs:
      s3-deploy-command: ${{ steps.deploy.outputs.s3-deploy-command }}

    steps:
      - name: Merge branch if auto-merge is enabled (${{ inputs.auto-merge-source-ref }} -> ${{ inputs.auto-merge-target-branch }})
        if: ${{ inputs.enable-auto-merge }}
        uses: everlytic/branch-merge@c4a244dc23143f824ae6c022a10732566cb8e973 # v1.1.5
        with:
          github_token: ${{ secrets.github-token }}
          target_branch: ${{ inputs.auto-merge-target-branch }}
          source_ref: ${{ inputs.auto-merge-source-ref }}

      - name: Setup Node.js and Install dependencies
        uses: gawaooooo-sandbox/learn-github-actions-custom/composite/node-setup-and-dependencies@v3
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}
          node-caching: ${{ inputs.node-caching }}
          npm-registry-url: ${{ inputs.npm-registry-url }}
          npm-scope: ${{ inputs.npm-scope }}
          node-auth-token: ${{ secrets.node-auth-token }}
          checkout-ref: ${{ inputs.checkout-ref }}
          npm-install-options: ${{ inputs.npm-install-options }}

      - name: Set environment variables
        uses: gawaooooo-sandbox/learn-github-actions-custom/composite/setup-environment-variables@v3
        with:
          environment-variables: ${{ inputs.build-environments }}

      - name: Build ${{ inputs.environment }}
        run: |
          set -x
          npm run ${{ inputs.build-command }}

      - name: Deploy to ${{ inputs.environment }} [${{ inputs.s3-sync-command }}]
        id: deploy
        uses: gawaooooo-sandbox/learn-github-actions-custom/composite/aws-s3-deploy-conditionally@v3
        with:
          environment: ${{ inputs.environment }}
          aws-role-arn: ${{ secrets.aws-role-arn }}
          aws-region: ${{ inputs.s3-aws-region }}
          s3-sync-command: ${{ inputs.s3-sync-command }}
          enable-aws-deploy: ${{ inputs.enable-aws-deploy }}
