# reusable workflow の ドキュメントを生成する
name: Generate actions / reusable workflow docs
run-name: ${{ github.workflow }}

on:
  pull_request:
    paths:
      - ".github/workflows/reusable-*.yml"
      - ".github/actions/**/action.yml"
permissions:
  contents: write
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# TODO: 更新されたファイルのみを対象にしたい
jobs:
  docs-lint:
    uses: ./.github/workflows/reusable-make-wf-docs.yml
    with:
      yaml-file: .github/workflows/reusable-lint.yml
      markdown-file: docs/reusable-lint.md
      ref: ${{ github.head_ref }}

  docs-make-wf-docs:
    uses: ./.github/workflows/reusable-make-wf-docs.yml
    with:
      yaml-file: .github/workflows/reusable-make-wf-docs.yml
      markdown-file: docs/reusable-make-wf-docs.md
      ref: ${{ github.head_ref }}

  docs-create-inputs-summary-actions-docs:
    uses: ./.github/workflows/reusable-make-wf-docs.yml
    with:
      yaml-file: .github/actions/create-inputs-summary/action.yml
      markdown-file: docs/actions/create-inputs-summary.md
      ref: ${{ github.head_ref }}
