# reusable workflow の ドキュメントを生成する
name: Generate actions / reusable workflow docs
run-name: ${{ github.workflow }}

on:
  pull_request:
    paths:
      - ".github/workflows/reusable-*.yml"
      - ".github/actions/**/action.yml"
permissions:
  contents: write
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    strategy:
      matrix:
        yaml-file:
          [
            github/workflows/reusable-lint.yml,
            .github/workflows/reusable-make-wf-docs.yml,
          ]
        ref: ${{ github.head_ref }}
        include:
          - yaml-file: github/workflows/reusable-lint.yml
            markdown-file: docs/reusable-lint.md
          - yaml-file: .github/workflows/reusable-make-wf-docs.yml
            markdown-file: docs/reusable-make-wf-docs.md
    uses: ./.github/workflows/reusable-make-wf-docs.yml
    with:
      yaml-file: ${{ matrix.yaml-file }}
      markdown-file: ${{ matrix.markdown-file }}
      ref: ${{ matrix.ref }}

  # docs-lint:
  #   uses: ./.github/workflows/reusable-make-wf-docs.yml
  #   with:
  #     yaml-file: .github/workflows/reusable-lint.yml
  #     markdown-file: docs/reusable-lint.md
  #     ref: ${{ github.head_ref }}

  # docs-make-wf-docs:
  #   uses: ./.github/workflows/reusable-make-wf-docs.yml
  #   with:
  #     yaml-file: .github/workflows/reusable-make-wf-docs.yml
  #     markdown-file: docs/reusable-make-wf-docs.md
  #     ref: ${{ github.head_ref }}

  # docs-create-inputs-summary-actions-docs:
  #   uses: ./.github/workflows/reusable-make-wf-docs.yml
  #   with:
  #     yaml-file: .github/actions/create-inputs-summary/action.yml
  #     markdown-file: docs/actions/create-inputs-summary.md
  #     ref: ${{ github.head_ref }}
