# reusable workflow の ドキュメントを生成する

name: Docs

on:
  pull_request:
    paths:
      - ".github/workflows/reusable-*.yml"
permissions:
  contents: write
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# TODO: 更新されたファイルのみを対象にしたい
jobs:
  docs-lint:
    uses: ./.github/workflows/reusable-make-wf-docs.yml
    with:
      yaml-file: .github/workflows/reusable-lint.yml
      markdown-file: docs/reusable-lint.md
      ref: ${{ github.head_ref }}

  docs-make-wf-docs:
    uses: ./.github/workflows/reusable-make-wf-docs.yml
    with:
      yaml-file: .github/workflows/reusable-make-wf-docs.yml
      markdown-file: docs/reusable-make-wf-docs.md
      ref: ${{ github.head_ref }}
