name: Label

on:
  workflow_call:
    inputs:
      sync-labels:
        description: |
          Optional. Controls whether labels should be removed if matching files are reverted or no longer changed by the pull request.
          Set to true to enable this behavior.
          Default: true
        type: boolean
        required: false
        default: true

      configuration-path:
        description: |
          Optional. Specifies the path to the label configuration file where label rules are defined.
          This file determines which labels should be applied based on file paths changed in the pull request.
          Default: .github/labeler.yml
        type: string
        required: false
        default: .github/labeler.yml

    secrets:
      repo-token:
        description: |
          Required. Token used to authorize label changes within the repository.
          This is typically set to the GITHUB_TOKEN provided by GitHub to interact with the GitHub API.
        required: true

jobs:
  triage:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: ${{ inputs.sync-labels }}
          configuration-path: ${{ inputs.configuration-path }}
