name: Label

on:
  workflow_call:
    inputs:
      sync-labels:
        description: |
          Controls whether labels should be removed if matching files are reverted or no longer changed by the pull request.
          Set to true to enable this behavior.
        type: boolean
        required: false
        default: true

      configuration-path:
        description: |
          Specifies the path to the label configuration file where label rules are defined.
          This file determines which labels should be applied based on file paths changed in the pull request.
        type: string
        required: false
        default: .github/labeler.yml

jobs:
  triage:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: ${{ inputs.sync-labels }}
          configuration-path: ${{ inputs.configuration-path }}
