name: Lint code

on:
  workflow_call:
    inputs:
      working-directory:
        description: |
          Specifies the directory where the workflow should execute.
          Use this to change the default context if your project has a specific structure.
        type: string
        required: false
        default: "."

      node-version:
        description: |
          Defines the version of Node.js to use.
          Specify a version number to ensure consistent runtime environments across different executions.
        type: string
        required: false

      node-version-file:
        description: |
          Path to a file containing the Node.js version requirement,
          overriding the 'node-version' input if both are specified.
        type: string
        required: false
        default: ".nvmrc"

      node-caching:
        description: |
          Configures caching for Node.js dependencies.
          Leave this as the default or set to an empty string to disable caching.
        type: string
        required: false
        default: "npm"

      npm-registry-url:
        description: |
          Sets the npm registry URL, which can be used to define custom registries for npm package installations.
        type: string
        required: false

      npm-scope:
        description: |
          Specifies the scope for npm package installations, affecting where packages are searched for and where they are published.
        type: string
        required: false

      checkout-ref:
        description: |
          Determines the specific reference (such as a branch, tag, or commit SHA) to checkout.
        type: string
        required: false
        default: ${{ github.head_ref }}

      npm-install-options:
        description: |
          Additional command-line options to pass to the `npm ci` command during dependencies installation.
        type: string
        required: false

      enable-format-check:
        description: |
          Enables a format check step within the workflow.
          Set to true to activate this step.
        type: boolean
        required: false
        default: false

      format-check-script:
        description: |
          The npm script to run for formatting checks.
          This is only used if `enable-format-check` is true.
        type: string
        required: false
        default: "npm run format:check"

      enable-lint:
        description: |
          Activates the linting step.
          Set to true to run lint checks.
        type: boolean
        required: false
        default: true

      lint-script:
        description: |
          The npm script to run for linting.
          This is used if `enable-lint` is true.
        type: string
        required: false
        default: "npm run lint"

      enable-type-check:
        description: |
          Turns on type checking as part of the workflow.
          Set to true to enforce type validations.
        type: boolean
        required: false
        default: false

      typecheck-script:
        description: |
          The npm script to run for type checks.
          This is used if `enable-type-check` is true.
        type: string
        required: false
        default: "npm run type-check"

    secrets:
      node-auth-token:
        description: |
          Authentication token used for npm commands, especially when accessing private packages or registries.
        required: false

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read
      packages: read
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Setup Node.js and Install dependencies
        uses: gawaooooo-sandbox/learn-github-actions-custom/composite/node-setup-and-dependencies@v3
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}
          node-caching: ${{ inputs.node-caching }}
          npm-registry-url: ${{ inputs.npm-registry-url }}
          npm-scope: ${{ inputs.npm-scope }}
          node-auth-token: ${{ secrets.node-auth-token }}
          checkout-ref: ${{ inputs.checkout-ref }}
          npm-install-options: ${{ inputs.npm-install-options }}

      - name: Run format check
        if: ${{ inputs.enable-format-check }}
        run: |
          set -xeu
          ${{ inputs.format-check-script }}

      - name: Run linter
        if: ${{ inputs.enable-lint }}
        run: |
          set -xeu
          ${{ inputs.lint-script }}

      - name: Run type check
        if: ${{ inputs.enable-type-check }}
        run: |
          set -xeu
          ${{ inputs.typecheck-script }}
