name: Test Workflow

on:
  workflow_call:
    inputs:
      test:
        description: |
          これはテストです
          テストです
        type: string
        required: false
        default: "test"

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create markdown test
        run: |
          set -xeu
          echo ${{ inputs.test }}
