# @see https://zenn.dev/tmknom/books/pragmatic-composite-action/viewer/docs
name: Docs

on:
  pull_request:
    paths:
      - "./github/workflows/reusable-*.yml"
  push:
permissions:
  contents: write
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    # env:
    #   # TODO: 複数ファイルに対してのREADME
    #   YAML_
    steps:
      - run: cat "${GITHUB_EVENT_PATH}"
